In [6]:
import numpy as np
import pandas as pd

# Exercise 1

## Question a)

In [19]:
sig_cpl = np.array([np.nan , 29.3 , 29.3 , 29.3 , 20.8 , 20.8 , 18.3 , 18.3 , 17.8 , 17.8 , 16.3 , 16.3 , 16.7 , 16.7 , 16.1 , 16.1 , 15.7 , 15.7 , 15.7 , 15.7])/100
T_i = np.arange(0,10,0.5)
t = 0
beta = 0.07
V_m = np.sqrt(sig_cpl**2*T_i * 2 * beta / (1 - np.exp(-2 * beta * T_i)))

In [43]:
V_m = V_m[~np.isnan(V_m)]


## Question b)

In [120]:
K = 0.035
LIBOR = np.array([4.228 , 2.791 , 3.067 , 3.728 , 3.728 , 4.051 , 4.051 , 4.199 , 4.199 , 4.45 , 4.45 , 4.626 , 4.626 , 4.816 , 4.816 , 4.96 , 4.96 , 5.088 , 5.088])/100
delta = 1/2
T_n = np.arange(2,11)

In [127]:
N = 100
M = 19
lettre = 100
Delto = 1/N
alpha = np.array([[0.00] * N]*M)
H = np.array([[0.00] * N]*M)
Pi = np.array([[0.00] * lettre]*len(T_n))

for t in range(len(T_n)):
    for k in range(lettre):
        B_star = np.array([1.0] * M)
        for m in range(M):
            H[m][0] = np.log(LIBOR)[m]
            for i in range(N-1):
                sig_m = V_m[m] * np.exp(-beta * (T_i[m] - T_n[t]*i*Delto))      
                for j in range(m):
                    alpha[m][i] = alpha[m][i] + delta * np.exp(H[j][i])/(1+delta * np.exp(H[j][i]))*sig_m - 1/2 * sig_m **2
                H[m][i+1] = H[m][i] + alpha[m][i] * Delto + sig_m * np.random.normal(1) * np.sqrt(Delto)
            B_star[m] = (1+ delta * np.exp(H[m-1][m-1]))*B_star[m-1]
            if T_i[m] >= T_n[t]:
                Pi[t][k] = Pi[t][k] + delta*np.maximum(np.exp(H[m][N-1]) - K,0)
        Pi[t][k] = Pi[t][k]/B_star[2*(t+2)]
            #import pdb; pdb.set_trace()


IndexError: index 20 is out of bounds for axis 0 with size 19

In [ ]:
B_star = np.array([1.0] * M)
for m in range(1,M):
    B_star[m] = (1+ delta * np.exp(H[m-1][m-1]))*B_star[m-1]

In [123]:
Pi

array([[2.8400224 , 2.47748758, 2.50833029, 2.26276564, 2.50869474,
        2.43740355, 2.33490829, 2.14130971, 1.74375455, 2.03062322,
        1.87005489, 2.20415424, 2.28830656, 1.97883365, 1.93579444,
        1.86507474, 1.73635701, 1.95976873, 1.37163015, 2.23804793,
        1.675668  , 1.50492534, 1.82218867, 1.59594985, 1.11739486,
        1.1561338 , 1.35247924, 1.82083896, 1.46253671, 1.16009796,
        1.1250929 , 1.16338689, 0.83966896, 0.80004537, 1.18505727,
        0.93673681, 1.11823398, 1.2297861 , 0.89837703, 0.91898752,
        1.00678355, 0.68031057, 0.91961371, 0.75452472, 0.90893668,
        1.01196711, 0.70676239, 0.69654785, 0.71358943, 0.70504473,
        0.91145451, 1.49238592, 0.84247275, 0.87212775, 0.7771962 ,
        0.80180183, 0.83962912, 0.88303624, 0.70400145, 0.40033911,
        0.57955192, 0.48164354, 0.64608892, 0.67619477, 0.9515752 ,
        0.56737358, 0.55637843, 0.95014307, 0.53411538, 0.81955193,
        0.62052691, 0.46937322, 0.92620562, 0.72

In [116]:
B_star

array([1.        , 1.02114   , 1.03586283, 1.04987157, 1.06741774,
       1.08423019, 1.10327255, 1.12033338, 1.1368153 , 1.15162291,
       1.16618481, 1.18155002, 1.19562465, 1.20769012, 1.22019279,
       1.23205073, 1.24425636, 1.25548967, 1.26577101])

In [119]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])